### ISSUE TITLE
Add Collect

### ISSUE THREAD

**Issue by Wolverin-e** [Wolverin-e/XDaemon#28]
- [ ] Add Collect as shown below & as in [v0.3-Δ spec](https://www.notion.so/v0-3-6e9c184578a541a0acbae03e8a069b6e).
```yml
name: Example-Backup-n-upload
schedule: 0 0 * * *

execute:
  backup:
    - basedir: /home/foo/some_server_dir
      resources:
        - resource1
        - resource2
        - resource3
      export: /home/bar/some-name-{timestamp}.zip
      upload: True
    - basedir: /home/bar
      resources:
        - resource1
        - resource2
        - resource3
      export: /home/bar/some-other-name-{timestamp}.zip

  collect:
    resources:
      - basedir: /foo/bar
        resources:
          - resource1.ext
          - resource2-dir
          - resource3
        backup-name: foo-bar
      - basedir: /bar/foo
        resources:
          - resource1.ext
          - resource2-dir
          - resource3
        backup-name: bar-foo
      - resource: /alpha/beta/res1.pdf
    export: /some/dir/export-{timestamp}.zip
    delete: True

  run:
    - exec: psql mydb > /foo/bar/mydb_dump-{timestamp}.sql
      upload_path: /foo/bar/mydb_dump-{timestamp}.sql

creds:
    connection_string: --
    container: --
```
